GET http://127.0.0.1:8000/api/tablepenjualan/0/2
###
GET http://127.0.0.1:8000/api/mounthjual/2021/12
###
GET http://127.0.0.1:8000/api/getallbarang
###
GET http://127.0.0.1:8000/api/tabledetailpenjual/0/10